# Generated by Django 3.1.3 on 2020-12-14 03:26

import catapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('origin', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'catapp_breed',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('hometype', models.CharField(choices=[('landed', 'Landed'), ('condominium', 'Condominium')], max_length=11)),
            ],
            options={
                'db_table': 'catapp_home',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('date_of_birth', models.DateField(validators=[catapp.models.date_in_past])),
                ('description', models.CharField(blank=True, max_length=300)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catapp.home')),
            ],
            options={
                'db_table': 'catapp_human',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1)),
                ('date_of_birth', models.DateField(validators=[catapp.models.date_in_past])),
                ('description', models.CharField(blank=True, max_length=300)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='catapp.breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to='catapp.human')),
            ],
            options={
                'db_table': 'catapp_cat',
                'ordering': ['name'],
            },
        ),
    ]
