# Generated by Django 3.1.1 on 2020-10-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0002_auto_20201014_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
