# Generated by Django 3.1.1 on 2020-10-14 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0005_human_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human',
            name='date_of_birth',
        ),
    ]
