# Generated by Django 3.1.1 on 2020-10-14 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0006_remove_human_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='human',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
