# Generated by Django 3.1.1 on 2020-10-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0007_human_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
