# Generated by Django 3.1.1 on 2020-10-16 04:00

import breeds.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breeds', '0008_auto_20201016_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='cat',
            name='date_of_birth',
            field=models.DateField(validators=[breeds.models.date_in_past]),
        ),
        migrations.AlterField(
            model_name='human',
            name='date_of_birth',
            field=models.DateField(validators=[breeds.models.date_in_past]),
        ),
    ]
